### ISSUE TITLE
tSNE-image.py throwing JSON serialization error

### ISSUE THREAD

**Issue by Michael-Day** [ml4a/ml4a-ofx#20]
I'm a complete Python/oF noob, and I'm trying to get the tSNE script example to work. Whenever I try and run the script, the process halts at the point where it tries to write the data. Here's the traceback:

Traceback (most recent call last):
File "tSNE-images.py", line 79, in <module>
   run_tsne(images_path, output_path, tsne_dimensions, tsne_perplexity, tsne_learning_rate)
  File "tSNE-images.py", line 69, in run_tsne
    json.dump(data, outfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 0.3274011 is not JSON serializable

I'm on macOS Sierra, if that helps. Is this a code issue, or am I just doing something daft? 
Thanks in advance for any help.

**Comment by genekogan** [comment]
this should be fixed as of latest release. please reopen if not.
