### ISSUE TITLE
Image t-SNE viewer

### ISSUE THREAD

**Issue by JohnTravolski** [ml4a/ml4a-ofx#36]
I'm trying to follow the tutorial here:
https://ml4a.github.io/guides/ImageTSNEViewer/
But when I run the following on Windows 10 64-bit:
`.\tSNE-images.py --images_path C:\Users\Rob\Downloads\imageTsne\test --output_path C:\Users\Rob\Downloads\imageTsne\out --perplexity 5`
where the `test` directory contains 16 images with arbitrary dimensions between 1920x1200 and 7680x4320, I get the following error:

```
Using TensorFlow backend.
WARNING:tensorflow:From C:\Program Files\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-04 01:06:11.358141: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractBlue13.jpg 0/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractBlue16.jpg 1/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractBlue20.jpg 2/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractBlueRed4.jpg 3/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractBrown1.jpg 4/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractRed4.jpg 5/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\AbstractYellow14.jpg 6/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Arena6.jpg 7/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Electricity7.jpg 8/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Flame2.jpg 9/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\GlowingOrb1.jpg 10/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Hurricane2.jpg 11/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Icicles1.jpg 12/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Soft1.jpg 13/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Swirl1.jpg 14/16
getting activations for C:\Users\Rob\Downloads\imageTsne\test\Waves3.jpg 15/16
Running PCA on 16 images...
Traceback (most recent call last):
  File "C:\Users\Rob\Downloads\imageTsne\ml4a-ofx-master\scripts\tSNE-images.py", line 94, in <module>
    run_tsne(images_path, output_path, tsne_dimensions, tsne_perplexity, tsne_learning_rate)
  File "C:\Users\Rob\Downloads\imageTsne\ml4a-ofx-master\scripts\tSNE-images.py", line 74, in run_tsne
    images, pca_features = analyze_images(images_path)
  File "C:\Users\Rob\Downloads\imageTsne\ml4a-ofx-master\scripts\tSNE-images.py", line 69, in analyze_images
    pca.fit(features)
  File "C:\Program Files\Python\Python37\lib\site-packages\sklearn\decomposition\pca.py", line 340, in fit
    self._fit(X)
  File "C:\Program Files\Python\Python37\lib\site-packages\sklearn\decomposition\pca.py", line 406, in _fit
    return self._fit_full(X, n_components)
  File "C:\Program Files\Python\Python37\lib\site-packages\sklearn\decomposition\pca.py", line 425, in _fit_full
    % (n_components, min(n_samples, n_features)))
ValueError: n_components=300 must be between 0 and min(n_samples, n_features)=16 with svd_solver='full'
```

I'm not sure what I need to do to solve this issue.  Here's the pip freeze if interested:
https://pastebin.com/NikSZs2u
Python 3.7.0

Any help would be greatly appreciated, I have no idea how to solve this issue.

**Comment by genekogan** [comment]
`ValueError: n_components=300 must be between 0 and min(n_samples, n_features)=16 with svd_solver='full'`
you don't have enough samples.
